#EXERCISE-2

Let $x_{ij}$ is a variable such that:
$$x_{ij}= \begin{cases} 
      0 & \text{if factory}\  i \text{ doesn't located at location}\ j\\
      1 & \text{if factory}\  i \text{ is located at location}\ j
   \end{cases}
$$
and also let that $c_{ij}$ is the setup cost of factory $i$ at location $j$.
and we have to minimize the costs of assigning
all the facilities to the locations. so our model will be:
$$\text{min} \sum_{i=1}^{12}\sum_{j=1}^{12}c_{ij}x_{ij}\\
  \text{s.t} \sum_{i=1}^{12}x_{ij}=1\\
  \sum_{j=1}^{12}x_{ij}=1\\
  x_{ij}\in\{0,1\}\ \forall\  i,j\in\{1,2,3,...,12\}$$


In [1]:
 !pip install -q pyomo

     |████████████████████████████████| 9.1 MB 7.0 MB/s 
     |████████████████████████████████| 49 kB 6.2 MB/s 


In [2]:
from pyomo.environ import *

In [3]:
import numpy as np

In [4]:
coef=np.loadtxt('lab5_ex2.txt')

In [5]:
print(coef)

[[22. 22. 19. 22. 22. 24. 18. 17. 21. 23. 19. 21.]
 [18. 12. 18. 19. 22. 21. 17. 20. 16. 17. 17. 24.]
 [19. 21. 17. 19. 17. 19. 24. 16. 18. 16. 20. 24.]
 [18. 24. 20. 21. 21. 21. 22. 19. 18. 21. 23. 23.]
 [23. 20. 19. 18. 20. 23. 22. 25. 24. 19. 21. 23.]
 [24. 16. 15. 16. 24. 21. 23. 21. 20. 20. 22. 19.]
 [22. 22. 21. 23. 18. 17. 16. 19. 24. 20. 20. 23.]
 [23. 17. 17. 17. 22. 24. 23. 20. 22. 19. 23. 21.]
 [21. 22. 21. 24. 20. 23. 19. 18. 23. 15. 25. 21.]
 [19. 19. 18. 19. 26. 24. 19. 17. 18. 20. 21. 20.]
 [20. 22. 23. 20. 22. 20. 20. 19. 17. 19. 20. 24.]
 [21. 25. 21. 19. 21. 19. 18. 16. 22. 24. 25. 24.]]


In [6]:
coef.shape

(12, 12)

In [7]:
M=12#number of rows
N=12#number of columns

In [8]:
model=ConcreteModel()

In [9]:
row_indices=np.arange(M)
col_indices=np.arange(N)

In [10]:
model.x=Var(col_indices,row_indices,domain=Binary)

In [11]:
model.objective=Objective(expr=sum(model.x[i,j]*coef[i,j] for j in col_indices for i in row_indices),sense=minimize)

In [12]:
model.constraints=ConstraintList()

In [13]:
for i in row_indices:
  model.constraints.add(sum(model.x[i,j] for j in col_indices)==1)
  

In [14]:
for j in col_indices:
  model.constraints.add(sum(model.x[i,j] for i in row_indices)==1)

In [15]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 1

In [16]:
!apt-get install -y -qq coinor-cbc

Selecting previously unselected package coinor-libcoinutils3v5.
(Reading database ... 148492 files and directories currently installed.)
Preparing to unpack .../0-coinor-libcoinutils3v5_2.10.14+repack1-1_amd64.deb ...
Unpacking coinor-libcoinutils3v5 (2.10.14+repack1-1) ...
Selecting previously unselected package coinor-libosi1v5.
Preparing to unpack .../1-coinor-libosi1v5_0.107.9+repack1-1_amd64.deb ...
Unpacking coinor-libosi1v5 (0.107.9+repack1-1) ...
Selecting previously unselected package coinor-libclp1.
Preparing to unpack .../2-coinor-libclp1_1.16.11+repack1-1_amd64.deb ...
Unpacking coinor-libclp1 (1.16.11+repack1-1) ...
Selecting previously unselected package coinor-libcgl1.
Preparing to unpack .../3-coinor-libcgl1_0.59.10+repack1-1_amd64.deb ...
Unpacking coinor-libcgl1 (0.59.10+repack1-1) ...
Selecting previously unselected package coinor-libcbc3.
Preparing to unpack .../4-coinor-libcbc3_2.9.9+repack1-1_amd64.deb ...
Unpacking coinor-libcbc3 (2.9.9+repack1-1) ...
Selecting p

In [17]:
opt_cbc=SolverFactory('cbc')

In [18]:
result=opt_cbc.solve(model)
print(result)


Problem: 
- Name: unknown
  Lower bound: 203.0
  Upper bound: 203.0
  Number of objectives: 1
  Number of constraints: 24
  Number of variables: 144
  Number of binary variables: 144
  Number of integer variables: 144
  Number of nonzeros: 144
  Sense: minimize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.01
  Wallclock time: 0.01
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.024378061294555664
Solution: 
- number of solutions: 0
  number of solutions displayed: 0



#Que.2(8)

In [19]:
print("Total optimal cost:-",model.objective())
print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value>0:
      print(f'factory {i+1} must be opened at location {j+1}')

Total optimal cost:- 203.0

Decision Variables
factory 1 must be opened at location 7
factory 2 must be opened at location 2
factory 3 must be opened at location 5
factory 4 must be opened at location 1
factory 5 must be opened at location 11
factory 6 must be opened at location 3
factory 7 must be opened at location 6
factory 8 must be opened at location 4
factory 9 must be opened at location 10
factory 10 must be opened at location 12
factory 11 must be opened at location 9
factory 12 must be opened at location 8


#Que.2(9)

In [20]:
model.x.domain=Reals

In [21]:
for i in row_indices:
  for j in col_indices:
    model.x[i,j].setlb(0)
    model.x[i,j].setub(1)

In [22]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   24 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5, 10), (5, 1

In [23]:
result=opt_cbc.solve(model)

In [24]:
print(result)


Problem: 
- Name: unknown
  Lower bound: 203.0
  Upper bound: 203.0
  Number of objectives: 1
  Number of constraints: 25
  Number of variables: 145
  Number of nonzeros: 144
  Sense: minimize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.0
  Wallclock time: 0.0
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: None
      Number of created subproblems: None
    Black box: 
      Number of iterations: 30
  Error rc: 0
  Time: 0.046530723571777344
Solution: 
- number of solutions: 0
  number of solutions displayed: 0



In [25]:
print("Total optimal cost:-",model.objective())
print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value>0:
      print(f'factory {i+1} must be opened at location {j+1},  i.e.  x[{i+1},{j+1}]={model.x[i,j].value}')

Total optimal cost:- 203.0

Decision Variables
factory 1 must be opened at location 7,  i.e.  x[1,7]=1.0
factory 2 must be opened at location 2,  i.e.  x[2,2]=1.0
factory 3 must be opened at location 5,  i.e.  x[3,5]=1.0
factory 4 must be opened at location 1,  i.e.  x[4,1]=1.0
factory 5 must be opened at location 11,  i.e.  x[5,11]=1.0
factory 6 must be opened at location 3,  i.e.  x[6,3]=1.0
factory 7 must be opened at location 6,  i.e.  x[7,6]=1.0
factory 8 must be opened at location 4,  i.e.  x[8,4]=1.0
factory 9 must be opened at location 10,  i.e.  x[9,10]=1.0
factory 10 must be opened at location 12,  i.e.  x[10,12]=1.0
factory 11 must be opened at location 9,  i.e.  x[11,9]=1.0
factory 12 must be opened at location 8,  i.e.  x[12,8]=1.0


#Que.2(10)

Yes,the optimal cost of both problems is same and the values of decision variables are still integer-valued.

we are getting same optimal value because when a variable(whose value increases gives the optimum value)starts increasing from zero then it increases to the maximum value.so that we can minimize the cost as much as possible that's why the values of decision variables are still integer-valued.


#Que.2(12)

since facility 2 cannot be assigned to location 4, facility
10 cannot be assigned to location 6 and facility 6 cannot be assigned to location 11,hence we will add some more constraints in our pyomo model.
those constraints will be:
$$x_{1,3}=0\\x_{9,5}=0\\x_{5,10}=0$$

In [26]:
model.constraints.add(expr=model.x[1,3]==0)
model.constraints.add(expr=model.x[9,5]==0)
model.constraints.add(expr=model.x[5,10]==0)

In [27]:
model.x.domain=Binary

In [28]:
model.pprint()

4 Set Declarations
    constraints_index : Size=1, Index=None, Ordered=Insertion
        Key  : Dimen : Domain : Size : Members
        None :     1 :    Any :   27 : {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27}
    x_index : Size=1, Index=None, Ordered=False
        Key  : Dimen : Domain              : Size : Members
        None :     2 : x_index_0*x_index_1 :  144 : {(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (0, 10), (0, 11), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 0), (2, 1), (2, 2), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (2, 10), (2, 11), (3, 0), (3, 1), (3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (3, 10), (3, 11), (4, 0), (4, 1), (4, 2), (4, 3), (4, 4), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (4, 10), (4, 11), (5, 0), (5, 1), (5, 2), (5, 3), (5, 4), (5, 5), (5, 6), (5, 7), (5, 8), (5, 9), (5

In [29]:
result=opt_cbc.solve(model)
print(result)


Problem: 
- Name: unknown
  Lower bound: 203.0
  Upper bound: 203.0
  Number of objectives: 1
  Number of constraints: 24
  Number of variables: 141
  Number of binary variables: 144
  Number of integer variables: 144
  Number of nonzeros: 141
  Sense: minimize
Solver: 
- Status: ok
  User time: -1.0
  System time: 0.01
  Wallclock time: 0.01
  Termination condition: optimal
  Termination message: Model was solved to optimality (subject to tolerances), and an optimal solution is available.
  Statistics: 
    Branch and bound: 
      Number of bounded subproblems: 0
      Number of created subproblems: 0
    Black box: 
      Number of iterations: 0
  Error rc: 0
  Time: 0.038988351821899414
Solution: 
- number of solutions: 0
  number of solutions displayed: 0



In [30]:
print("Total optimal cost:-",model.objective())
print('\nDecision Variables')
for i in row_indices:
  for j in col_indices:
    if model.x[i,j].value>0:
      print(f'factory {i+1} must be opened at location {j+1}')

Total optimal cost:- 203.0

Decision Variables
factory 1 must be opened at location 7
factory 2 must be opened at location 2
factory 3 must be opened at location 5
factory 4 must be opened at location 1
factory 5 must be opened at location 11
factory 6 must be opened at location 3
factory 7 must be opened at location 6
factory 8 must be opened at location 4
factory 9 must be opened at location 10
factory 10 must be opened at location 12
factory 11 must be opened at location 9
factory 12 must be opened at location 8


After adding three more restriction in our model,the optimal cost is same as before because in the previous optimal solution these restriction were already fulfilled so adding these restriciton didn't make any impact on the solution.